/* One Word · Advanced. Seven letters, seven tries. Each word carries a teaching one layer deeper than the regular edition: a move you can make at work tomorrow. Picked by day number from October 2, 2026, the same clock as the regular word. */
window.BANK7=[
["CONTEXT","Context is everything the model can see when it answers: your message, the files you attached, the earlier turns. Tomorrow, before you ask, paste the one document that matters and say what it is for. Better context beats a cleverer prompt."],
["HANDOFF","A handoff is the moment work passes from you to an AI or back. Write down what done looks like before you hand anything over, and ask for a short note of what changed when it comes back."],
["PRIVACY","Anything you paste into a chat may be stored by the company that runs it. Before you share client names, health details or money figures, check your plan's data settings, and swap real names for placeholders when you can."],
["RECEIPT","Ask your AI for a receipt: a short list of what it read, what it changed and what it was unsure about. Receipts turn a black box into a record you can check in two minutes."],
["SOURCES","When an AI states a fact, ask for its sources and open at least one. If it cannot point to where a claim came from, treat that claim as a guess until you confirm it."],
["CHARTER","A charter is one page that tells an AI who it works for, what it may do and what it never does. Write one for your most used assistant and paste it at the top of every new session."],
["JOURNAL","Keep a work journal your AI can read: three lines a day on what you did and what is next. Tomorrow it can pick up where today ended, and so can you."],
["PATTERN","When you fix the same AI mistake twice, you have found a pattern. Write the fix as a rule, add it to your house rules, and the mistake stops coming back."],
["AGENTIC","Agentic means the AI takes several steps on its own: it searches, drafts and files. Start agents on work you can easily undo, like drafts and labels, before you let them send or delete anything."],
["CHATBOT","A chatbot answers in the moment and forgets. For work that repeats, move from the chat window to a saved instruction or a project, so the setup is done once and reused."],
["COMPUTE","Compute is the processing power a model uses, and bigger models use more of it for every answer. Use the small, fast model for quick drafts and save the large one for the hard thinking."],
["DATASET","A dataset is the collection of examples a model learned from or that you hand it. Ten clean, labeled examples of your real work will teach your AI more than a page of instructions."],
["EXAMPLE","Show, then tell. Paste one example of the output you want, a past email or a finished report, and ask for the same shape. Examples carry tone and format faster than any description."],
["INSIGHT","An AI can sort and summarize at speed, but the insight is still yours to name. After any AI summary, write one sentence of your own: what this means for us, and what we do next."],
["LIBRARY","Build a prompt library: the five instructions you use every week, saved where your team can find them. A shared library turns one person's trick into everyone's default."],
["MACHINE","A model is a machine for predicting the next word, very well. It can sound sure and still be wrong, so read its confidence as style, and check anything that matters."],
["NETWORK","A neural network learns by adjusting millions of small numbers until its guesses improve. Nobody wrote its rules by hand, which is why we test what it does before we rely on it."],
["OUTCOME","Ask for outcomes. Tell your AI what the reader should know or do when they finish, and let it work backward from there."],
["PREVIEW","Never let an AI send what you have not previewed. Turn on draft mode wherever you can, so the first time anyone sees the work, a person has already read it."],
["PROCESS","Map the process before you automate it. Write the steps as you really do them today, mark the dull ones, and hand only those to the machine."],
["PROJECT","Most assistants let you group chats into a project with shared files and instructions. Set one up per client or per job, so the background is already there in every new chat."],
["QUALITY","Agree on what good looks like before you judge the output. A three point checklist for quality, read every time, beats a vague feeling that something is off."],
["REFLECT","Ask your AI to reflect before it answers: list what it is unsure about, then answer. Naming the uncertainty first catches a surprising number of mistakes."],
["RHYTHMS","Give AI work a rhythm: a morning sort of the inbox, a midday check, an end of day note. Work that runs on a rhythm gets reviewed, and work that gets reviewed gets better."],
["RITUALS","Small team rituals make AI use visible: a weekly five minutes where each person shares one thing that worked. What gets shown gets copied."],
["SCRIPTS","Some tasks repeat exactly. Ask an AI to write a small script for them once, test it on a copy, and you never do that task by hand again."],
["SESSION","A session is one stretch of conversation, and long sessions drift. When answers start to wander, start fresh with a short summary of where you are."],
["STATION","Give each AI tool a station, one clear job, the way a kitchen gives each cook a station. One assistant for email, another for research, and nobody reaches across the line."],
["SUMMARY","Ask for the summary you would want to receive: three lines, decisions first, then open questions. Then check that each line is really in the source."],
["TESTING","Test an AI workflow on last month's work before you run it on this month's. You already know the right answers, so the mistakes show up right away."],
["TRAINED","A model is trained up to a date and knows little after it. For anything recent, give it the article or the numbers yourself."],
["UPGRADE","Models get upgraded often, and the same prompt can behave differently after an upgrade. Keep two or three saved test prompts and rerun them when your tool changes."],
["VERSION","Keep versions. Save the draft before you ask an AI to revise it, so you can compare, and so a bad edit never costs you the good one."],
["WEIGHTS","A model's weights are the millions of learned numbers that hold what it knows. Open weight models can run on your own computers, which matters when your data cannot leave the building."],
["ALIGNED","An aligned AI does what its people actually intend, safely. Inside a team, alignment starts smaller: everyone agrees on what the AI may do, and writes it down."],
["CONSENT","Ask before you record a meeting or run someone's words through AI. Consent keeps trust intact, and in many places the law requires it."],
["OVERSEE","Someone should oversee every AI workflow by name. When a person owns it, problems get noticed and fixed early."],
["EXPLAIN","If you cannot explain how an AI result was made, do not sign your name to it. Ask the AI to explain its steps in plain words, then decide."],
["LICENSE","Check the license before you publish AI made images or code. Some tools restrict commercial use, and your client will ask."],
["COPILOT","A copilot sits beside you and suggests while you keep the controls. Accept suggestions one at a time and read each one, especially in code and in numbers."],
["RECIPES","A recipe is a working system you can hand to someone else: the prompt, the rules and the rhythm. Write your best AI habit as a recipe card and give it to a teammate."],
["KITCHEN","Run AI work like a kitchen: stations, a pass where everything is checked before it goes out, and a cleanup at the end of the shift. Order makes speed safe."],
["PARTNER","Treat your AI as a partner with a role: give it a name for the job, the rules it works by and a record it keeps. A partner like that gets better every week."],
["RESPECT","Respect the people on the other end of AI work. If a message would feel cold coming from you, it is cold coming from your assistant, so rewrite it."],
["REVIEWS","Build reviews into the work: a person reads before anything goes out, and a weekly look at what slipped. Reviews are how a team learns what to trust."],
["CAPTION","Caption what AI made. A short note like drafted with AI, reviewed by Dana tells readers how the work was made and who stands behind it."],
["HONESTY","Be honest about what AI did. Teams that say so openly learn faster, because the good habits get shared."],
["BUDGETS","Set budgets for AI use: a monthly cap on spend and a note on which tasks deserve the large models. Costs stay predictable, and nobody gets a surprise bill."]
];
